/**
 * Created by ianchen on 2016/11/25.
 */

import React from 'react';
import {Platform} from 'react-native';
const PushNotification = require('react-native-push-notification');

// configure 配置项必须调用，否则iOS系统下无法推送，Android则不行
// ************** 另记：iOS 本地推送，仅在程序处于后台运行时，顶部才会给出 alert 提示，并有推送提示音，Android则无关前后台 **************
if (Platform.OS === 'ios') {
    PushNotification.configure({
        // (required) Called when a remote or local notification is opened or received
        onNotification: function (notification) {
            // console.log('NOTIFICATION:', notification);
        },

        // IOS ONLY (optional): default: all - Permissions to register.
        permissions: {
            alert: true,
            badge: true,
            sound: true
        },

        // Should the initial notification be popped automatically
        // default: true
        popInitialNotification: true,

        /**
         * (optional) default: true
         * - Specified if permissions (ios) and token (android and ios) will requested or not,
         * - if not, you must call PushNotificationsHandler.requestPermissions() later
         */
        requestPermissions: true,
    });
} else {
    PushNotification.configure({
        // (required) Called when a remote or local notification is opened or received
        onNotification: function (notification) {
            console.log('NOTIFICATION:', notification);
        },

        // Should the initial notification be popped automatically
        // default: true
        popInitialNotification: true,

        /**
         * (optional) default: true
         * - Specified if permissions (ios) and token (android and ios) will requested or not,
         * - if not, you must call PushNotificationsHandler.requestPermissions() later
         */
        requestPermissions: true,
    });
}

const notifaction = {
    localPush: (title, message) => {
        if (Platform.OS === 'ios') {
            PushNotification.localNotification({
                /* iOS only properties */
                alertAction: 'action',// (optional) default: view
                category: 'REACT_NATIVE',// (optional) default: null
                // userInfo: // (optional) default: null (object containing additional notification data)

                /* iOS and Android properties */
                title: title, // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
                message: message, // (required)
                playSound: true, // (optional) default: true
                soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
                // number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            });
        } else {
            PushNotification.localNotification({
                /* Android Only Properties */
                // id: '100', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
                // ticker: "My Notification Ticker", // (optional)
                autoCancel: false, // (optional) default: true
                // largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
                // smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
                // bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
                // subText: "This is a subText", // (optional) default: none
                // color: "red", // (optional) default: system default
                vibrate: true, // (optional) default: true
                vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
                tag: 'zoe_rus_local_tag', // (optional) add tag to message
                group: "zoe_rus_local_group", // (optional) add group to message
                ongoing: false, // (optional) set whether this is an "ongoing" notification

                /* iOS and Android properties */
                title: title, // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
                message: message, // (required)
                playSound: true, // (optional) default: true
                soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
                // number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            });
        }
    },
    localPushTask: (message, sec) => {
        PushNotification.localNotificationSchedule({
            message: message,
            date: new Date(Date.now() + (sec * 1000))
        });
    },
    // getNotifaction: () => {
    //     return PushNotification;
    // }
}

module.exports = notifaction;